In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\kerem\Desktop\pandas\data\imdb.csv')

df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [2]:
(
    df.query('Year > 2000')
        .loc[:, ['Year', 'Votes']]
        .sort_values(by='Year', ascending=True)
)

     Year   Votes
773  2006   82701
445  2006  184152
99   2006  937414
550  2006  106381
885  2006  253417
..    ...     ...
247  2016   14708
250  2016     178
258  2016   69823
237  2016    4895
999  2016   12435

[1000 rows x 2 columns]

In [3]:
(
    df[df['Year'] > 2000]
        .sort_values(by='Rating', ascending=False)
        [['Title', 'Year', 'Director']]
        .head(12)
)

                     Title  Year                          Director
54         The Dark Knight  2008                 Christopher Nolan
80               Inception  2010                 Christopher Nolan
117                 Dangal  2016                     Nitesh Tiwari
36            Interstellar  2014                 Christopher Nolan
96           Kimi no na wa  2016                    Makoto Shinkai
249       The Intouchables  2011                   Olivier Nakache
133               Whiplash  2014                   Damien Chazelle
64            The Prestige  2006                 Christopher Nolan
99            The Departed  2006                   Martin Scorsese
991       Taare Zameen Par  2007                        Aamir Khan
124  The Dark Knight Rises  2012                 Christopher Nolan
476    The Lives of Others  2006  Florian Henckel von Donnersmarck

In [4]:
(
    df.query('Year > 2000')
        .sort_values(by='Rating', ascending=False)
        [['Title', 'Year', 'Director']]
        .head(12)
)

                     Title  Year                          Director
54         The Dark Knight  2008                 Christopher Nolan
80               Inception  2010                 Christopher Nolan
117                 Dangal  2016                     Nitesh Tiwari
36            Interstellar  2014                 Christopher Nolan
96           Kimi no na wa  2016                    Makoto Shinkai
249       The Intouchables  2011                   Olivier Nakache
133               Whiplash  2014                   Damien Chazelle
64            The Prestige  2006                 Christopher Nolan
99            The Departed  2006                   Martin Scorsese
991       Taare Zameen Par  2007                        Aamir Khan
124  The Dark Knight Rises  2012                 Christopher Nolan
476    The Lives of Others  2006  Florian Henckel von Donnersmarck

In [5]:
(
    df.query('2000 < Year < 2025')
        .loc[:, ['Title', 'Rating', 'Director']]
        .sort_values(by='Director', ascending=True)
)

                                  Title  Rating             Director
991                    Taare Zameen Par     8.5           Aamir Khan
311                      La vie d'Adèle     7.8  Abdellatif Kechiche
783                              Tramps     6.5            Adam Leon
142                       The Big Short     7.8           Adam McKay
469                      The Other Guys     6.7           Adam McKay
..                                  ...     ...                  ...
60   Batman v Superman: Dawn of Justice     6.7          Zack Snyder
294                        Man of Steel     7.1          Zack Snyder
285                        Sucker Punch     6.1          Zack Snyder
113                                 300     7.7          Zack Snyder
604               The Rise of the Krays     5.1        Zackary Adler

[1000 rows x 3 columns]

In [6]:
(
    df[
        (df['Title'].str.contains('King', na=False)) &
        (df['Rating'] > 7.0)
    ]
    [['Title', 'Rating', 'Director']]
    .sort_values(by='Rating', ascending=False)
)

                            Title  Rating             Director
685             The King's Speech     8.0           Tom Hooper
485              Moonrise Kingdom     7.8         Wes Anderson
65   Kingsman: The Secret Service     7.7       Matthew Vaughn
953           The Kings of Summer     7.2  Jordan Vogt-Roberts

In [7]:
df[
    (df['Title'].str.contains('King', na=False)) & (df['Rating'] > 7.0)
][['Title', 'Rating', 'Actors']].sort_values(by='Rating', ascending=False)

,Title,Rating,Actors
685,The King's Speech,8.0,"Colin Firth, Geoffrey Rush, Helena Bonham Cart..."
485,Moonrise Kingdom,7.8,"Jared Gilman, Kara Hayward, Bruce Willis, Bill..."
65,Kingsman: The Secret Service,7.7,"Colin Firth, Taron Egerton, Samuel L. Jackson,..."
953,The Kings of Summer,7.2,"Nick Robinson, Gabriel Basso, Moises Arias,Nic..."

In [8]:
# path1 — quick one-liner (note: .sum() with parentheses, not .sum)
path1 = df.groupby(by='Year')['Votes'].sum()
print(path1)

# path2 — chained, sorted descending by total votes
path2 = (
    df.groupby(by='Year')
        .agg({'Votes': 'sum'})
        .sort_values(by='Votes', ascending=False)
)
path2

Year
2006    11848758
2007    12949545
2008    14326280
2009    13044813
2010    15166939
2011    15169789
2012    18254470
2013    19933518
2014    19985162
2015    14697230
2016    14431751
Name: Votes, dtype: int64

         Votes
Year
2014  19985162
2013  19933518
2012  18254470
2011  15169789
2010  15166939
2015  14697230
2016  14431751
2008  14326280
2009  13044813
2007  12949545
2006  11848758

In [9]:
df['Director'].nunique()

644