In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\kerem\Desktop\pandas\data\imdb.csv')

df.head()

     Year   Votes
918  2006  199387
924  2006  246797
901  2006  118905
908  2006   64351
885  2006  253417
..    ...     ...
5    2016   56036
6    2016  258682
7    2016    2490
8    2016    7188
999  2016   12435

[1000 rows x 2 columns]

In [ ]:
(
    df.query('Year > 2000')
            .loc[:,['Year','Votes']]
            .sort_values(by='Year',ascending = True)
)

In [ ]:
(
    df[df['Year'] > 2000]
    .sort_values(by='Rating', ascending=False)
    [['Title', 'Year', 'Director']]
    .head(12)
)

                     Title  Year                          Director
54         The Dark Knight  2008                 Christopher Nolan
80               Inception  2010                 Christopher Nolan
117                 Dangal  2016                     Nitesh Tiwari
36            Interstellar  2014                 Christopher Nolan
249       The Intouchables  2011                   Olivier Nakache
96           Kimi no na wa  2016                    Makoto Shinkai
64            The Prestige  2006                 Christopher Nolan
99            The Departed  2006                   Martin Scorsese
476    The Lives of Others  2006  Florian Henckel von Donnersmarck
124  The Dark Knight Rises  2012                 Christopher Nolan
133               Whiplash  2014                   Damien Chazelle
991       Taare Zameen Par  2007                        Aamir Khan

In [ ]:
(
    df.query('Year > 2000')
        .sort_values(by='Rating', ascending=False)
        [['Title', 'Year', 'Director']]
    .head(12)
)

                     Title  Year                          Director
54         The Dark Knight  2008                 Christopher Nolan
80               Inception  2010                 Christopher Nolan
117                 Dangal  2016                     Nitesh Tiwari
36            Interstellar  2014                 Christopher Nolan
249       The Intouchables  2011                   Olivier Nakache
96           Kimi no na wa  2016                    Makoto Shinkai
64            The Prestige  2006                 Christopher Nolan
99            The Departed  2006                   Martin Scorsese
476    The Lives of Others  2006  Florian Henckel von Donnersmarck
124  The Dark Knight Rises  2012                 Christopher Nolan
133               Whiplash  2014                   Damien Chazelle
991       Taare Zameen Par  2007                        Aamir Khan

In [ ]:
(
    df.query('2000 < Year < 2025')
        .loc[: , ['Title','Rating','Director']]
        .sort_values(
        by='Director',
        ascending=True
    
    
)
)

                                  Title  Rating             Director
991                    Taare Zameen Par     8.5           Aamir Khan
311                      La vie d'Adèle     7.8  Abdellatif Kechiche
783                              Tramps     6.5            Adam Leon
142                       The Big Short     7.8           Adam McKay
469                      The Other Guys     6.7           Adam McKay
..                                  ...     ...                  ...
60   Batman v Superman: Dawn of Justice     6.7          Zack Snyder
294                        Man of Steel     7.1          Zack Snyder
285                        Sucker Punch     6.1          Zack Snyder
113                                 300     7.7          Zack Snyder
604               The Rise of the Krays     5.1        Zackary Adler

[1000 rows x 3 columns]

In [ ]:
(
    df[
        (df['Title'].str.contains('King', na=False)) & 
        (df['Rating'] > 7.0)
    ]
    [['Title', 'Rating', 'Director']]
    .sort_values(by='Rating', ascending=False)
)

                            Title  Rating             Director
685             The King's Speech     8.0           Tom Hooper
485              Moonrise Kingdom     7.8         Wes Anderson
65   Kingsman: The Secret Service     7.7       Matthew Vaughn
953           The Kings of Summer     7.2  Jordan Vogt-Roberts

In [ ]:
df[
    (df['Title'].str.contains('King')) & (df['Rating'] > 7.0)
][['Title', 'Rating', 'Actors']].sort_values(by='Rating', ascending=False)

,Title,Rating,Actors
685,The King's Speech,8.0,"Colin Firth, Geoffrey Rush, Helena Bonham Cart..."
485,Moonrise Kingdom,7.8,"Jared Gilman, Kara Hayward, Bruce Willis, Bill..."
65,Kingsman: The Secret Service,7.7,"Colin Firth, Taron Egerton, Samuel L. Jackson,..."
953,The Kings of Summer,7.2,"Nick Robinson, Gabriel Basso, Moises Arias,Nic..."

In [ ]:
#path1 
df.groupby(by='Year')['Votes'].sum

#path2
(
    df.groupby(by='Year')
        .agg({
            'Votes':sum
        })
        .sort_values(
            by='Votes',
            ascending=False
        )
)

C:\Users\kerem\AppData\Local\Temp\ipykernel_11896\416528571.py:7: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg({

         Votes
Year
2014  19985162
2013  19933518
2012  18254470
2011  15169789
2010  15166939
2015  14697230
2016  14431751
2008  14326280
2009  13044813
2007  12949545
2006  11848758

In [ ]:
df['Director'].nunique()

644